### ISSUE TITLE
Error on creating new widget

### ISSUE THREAD

**Issue by deepartiwani** [objectedge/occ-tools#41]
While generating new widget through occ-tools, it is giving 'Bad Credentials' error 

info: Loading hooks modules...
info:  
info: Triggering hook occ-tools-init
info:  
info: Generating widget "msiCountrySelection"...
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
    at RequestError.get (/home/deeparti.wani/projects/occ-tools/node_modules/@octokit/request-error/dist-node/index.js:29:17)
    at OccTools.fini (/home/deeparti.wani/projects/occ-tools/src/commands/OccTools.js:187:63)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'Deprecation'
}
error: Bad credentials

**Comment by deepartiwani** [comment]
updating github token in config.json will help to resolve the issue.
